### PR TITLE
Fix compatibility with React 16

### LINKED ISSUE #274: Deprecation warning with React 15.5
Looks like React.PropTypes is deprecated, which means when using FluxComponent you get the following deprecation warning:

```
Warning: Accessing PropTypes via the main React package is deprecated.
Use the prop-types package from npm instead.
```

More info here: https://facebook.github.io/react/warnings/dont-call-proptypes.html

### PR DESCRIPTION
**Pull request by ai**
I replaced `React.PropTypes` to separated `PropTypes` package to fix:

* Warning in React 15.5.
* React 16 support.

Fixes #274

@voronianski everything is good for small patch release?

### CODE REVIEW

**Comment by ai** [comment]
@voronianski any comments?

**Comment by ai** [comment]
@voronianski ping :)

**Review by voronianski — APPROVED** [review]

**Comment by voronianski** [comment]
@ai sorry for a delay

**Comment by voronianski** [comment]
@ai btw I can make you a collaborator rights if you want, because I actually don't have projects that use Flummox anymore..

**Comment by ai** [comment]
@voronianski I plan to migrate to Logux in next few months :(

**Pull request merged**
