### PR TITLE
Store: Register to all actions at once

### PR DESCRIPTION
**Pull request by hugobessaa**
This PR addresses #69.

It implements `Store#registerAll()` to register a function to handle all actions. It depended on a way to get all action ids available, so I also implemented `Flux#getAllActionIds()` that returns an array of action ids, instead of an object as `Flux#getActionIds()` does.

Is this the right way to solve this problem? If so, I can continue and implement `Store#registerMatcher()` and complete the code test coverage :smile:.

This is my first PR here.

### CODE REVIEW

**Comment by tappleby** [comment]
A few possible issues I see with this implementation:
- `registerAll` assumes that all actions you want to listen to are already registered on the flux instance at the time of calling it.
- I dont think this will handle async actions.
- Im not sure if its necessary to register a separate handler for each action when you want to listen to them all.

I wonder if this could be handled with an additional `_catchAllHandlers` array on the store, or possibly we could check if a method is defined on the store. eg. `handleAll`.

@acdlite thoughts?

**Comment by hugobessaa** [comment]
Yes, I was also thinking about this. Would simplify things, but it also
means an action could fire more than one handler if you registerAll() and
register()

Is this a problem? We can solve it by trying to call the registered handler
and falling back to the "all" one.

Please share your thoughts on this :)
Em qui, 12 de mar de 2015 às 01:41, Terry Appleby <notifications@github.com>
escreveu:

**Comment by acdlite** [comment]
I've been meaning to open a separate issue about this, but I do think it should be possible for a single store to register multiple handlers for the same action. Currently a second call to `Store#register()` will override the first.

But that's probably outside the scope of this PR.

I think a better way to handle this would be, like @tappleby suggests, to store handers registered with `registerAll()` in a private store variable like `_catchAllHandlers`. Then inside `Store#handler()`, loop through them and send them them payload. It will require some significant refactoring of `handler()`, but it's in need of some refactoring anyway.

**Comment by hugobessaa** [comment]
I changed some things

`Store#registerAll()` add `_catchAllHandler` and `Store#registerAllAsync()` add `_catchAllAsyncHandlers`  on the Store.

`Store#handler()` were refactored to use the new `Store#_performHandlers()` instead of `Store#_performHandler()`.

`Store#_performHandlers()` gets an array of handlers and an array of args and executes each handler with args via `Store#_performHandler()`.

`Store#_performHandlers()` can be used in the future when we implement a way to register many handlers to the same actions.

These changes fixes all the problems pointed by @tappleby

**Comment by hugobessaa** [comment]
I also rebased the branch with the current master. As there were a major version bump, this prevents too much conflicts when trying to merge.

**Comment by acdlite** [comment]
Thanks! Busy with some other stuff, but I'll try to get this merged this weekend.

**Comment by hugobessaa** [comment]
Needs some more tests. Is the API now ok? What's your thoughts @tappleby ?

**Comment by tappleby** [comment]
if we want to allow support for `registerMatcher` type api mentioned in #69 will need to allow for multiple `_catchAllHandlers` (same applies to the async handlers).

Also to avoid multiple change events being emitted we probably want to execute the handlers [here](https://github.com/hugobessaa/flummox/blob/register-all-matcher/src/Store.js#L188) so `_isHandlingDispatch` and `_pendingState` are initialized. Calling the handlers in that spot would cause issues if you needed to access state set by a previous handler, trying to think of a situation where this would be necessary.

**Comment by hugobessaa** [comment]
I just implemented @tappleby's suggestions. Just "all" handlers (registered with `Store#registerAll[Async]()`) can be registered multiple times. I plan to add multiple handler support to specific actions too, as we evolve this PR.

@tappleby: I couldn;t understand how one handler could not access the state set by a previous handler. Each time `Store#setState()` or `Store#replaceState()` is called, the `Store._pendingState` is updated. This alone enables handler composition, as far as I know.

**Comment by acdlite** [comment]
Can you add tests, please?

**Comment by hugobessaa** [comment]
Tests added :smile:. Please point improvements I could do to the tests. Not so used to test yet.

**Comment by acdlite** [comment]
@hugobessaa Merged! Thank you! Could you add to the Store docs, please? https://github.com/acdlite/flummox/blob/master/docs/docs/api/store.md

**Comment by hugobessaa** [comment]
Awesome! I'll add it now :)

**Comment by chicoxyzzy** [comment]
great feature. BTW can't find it in docs

**Pull request merged**
