### PR TITLE
Better React integration (mixin + component)

### PR DESCRIPTION
**Pull request by acdlite**
A React component mixin. Does two things:

1. Expects Flux instance to be passed to components either as a prop `flux` or as context `flux`. Exposes it as `this.flux` for convenience.
2. Adds method `connectToStore()`. This method handles getting the initial state from a single store or collection of stores, as well as adding/removing change event listeners and updating component state. Check out the source for inline documentation.

Looking for feedback on this. Tried to cover the general case, without being too "clever."

### CODE REVIEW

**Comment by acdlite** [comment]
I like how Reflux's mixin is a one-liner. Would be pretty easy to make this work more like that.

**Comment by acdlite** [comment]
BTW, this isn't final at all: I wrote most of this yesterday, before I saw the implementations posted in #17. Let's keep the discussion going.

@SimonDegraeve @martintietz

**Comment by martintietz** [comment]
Looks good to me. Just one question - is it required to define the contextTypes property both inside the mixin and inside the ContextComponent?

**Comment by acdlite** [comment]
Ah, that's a good catch. No, I just forgot to get rid of it in the ContextComponent as I was writing the tests :D

**Comment by acdlite** [comment]
I updated the mixin to be a function whose arguments are passed to `connectToStores()` and used to set the initial state.

Now using is just a single function call, like this:

```js
let Component = React.createClass({
  mixins: [ReactMixin({
    storeA: store => ({
      foo: store.state.a,
    }),
    storeB: store => ({
      bar: store.state.b,
    })
  }]
});
```

That will handle the initial state, subscribing to state updates, and unsubscribing. If an array of keys is passed instead, then the entire state of each store is merged into the component state.

In case you're wondering, the reason I'm using a getter function here instead of, say, state keys a la Reflux is because this lets us use any getter methods defined on the store.

Thoughts?

**Comment by martintietz** [comment]
Is your getter method bound to the context of the component? E.g., could I call ```this.someFunctionInsideMyComponent()``` inside the getter function?

**Comment by acdlite** [comment]
@martintietz No. What's the use case for that?

**Comment by acdlite** [comment]
I guess there's no reason it shouldn't be, though.

**Comment by martintietz** [comment]
Just one example that comes to my mind: https://github.com/gaearon/flux-react-router-example/blob/master/scripts/pages/RepoPage.js#L30 So you want to get data from your store depending on some parameters (whatever it may be, e.g. some URL parameters that you access via the [state mixin](https://github.com/rackt/react-router/blob/master/docs/api/mixins/State.md) from react-router).

**Comment by acdlite** [comment]
@martintietz That's a great point. I'll update.

**Comment by acdlite** [comment]
@martintietz Updated!

**Comment by acdlite** [comment]
Alright, so this is pretty cool: Because components > mixins, I made a component form of this mixin. Here's how you use it (using an ES6 class component here):

```js
class ParentComponent extends React.Component {

  render() {
    <FluxComponent connectToStore="fooStore">
      <ChildComponent>
    </FluxComponent>
  }

}
```

ChildComponent in this example is given prop `flux` with the flux instance. It is also given props that stay in sync with the state of fooStore. So if fooStore has state `{ foo: 'bar', bar: 'baz' }`, then ChildComponent has props `foo="bar"` and `bar="baz"`.

The component assumes that the flux instance is available as context. An easy way to do that is to do this near the top of the app hierarchy:

```js
<FluxComponent flux={flux}>
  ...children
</Flux>
```

Just pass the flux instance as a prop and all children will have access to it as context.

The practical upshot of all this is that the mixin, subscribing to state changes, and context are now simply implementation details.

I really think this could be an elegant solution to integrating Flummox with React. Docs will need to be very clear about how to use it, though.

Thoughts?

**Comment by acdlite** [comment]
@martintietz @SimonDegraeve @vesparny If nobody has any further feedback, I'm going to merge this in. Tried it out one of my projects and it works well.

**Comment by acdlite** [comment]
Oh man... I'm testing this out by trying it in an existing app, and I just got rid of soooo much code. Really excited about this.

**Comment by vesparny** [comment]
@acdlite just integrated this new feature in a small project and it really works well. Lot of boilerplate code removed and cleaner components.
I definitely prefer the Mixin form for that though.

**Pull request merged**
