### PR TITLE
TestUtils simulate actions

### PR DESCRIPTION
**Pull request by tappleby**
This PR implements the TestUtils simulate api discussed in #35.

The API is implemented but the docs still need to be finished.

### CODE REVIEW

**Comment by acdlite** [comment]
Looks great! Do you mind changing the indents to two spaces to match the rest of the repo?

**Comment by acdlite** [comment]
I think the file should be `test-utils.js` instead of `testutils.js`.

**Comment by tappleby** [comment]
two spaces + `test-utils.js` have been pushed.

**Comment by acdlite** [comment]
Awesome! Merged and released in 2.11

**Comment by tappleby** [comment]
The docs for the [TestUtils](https://github.com/acdlite/flummox/blob/master/docs/api/TestUtils.md) are still just a shell, I wont be able to write anything for these until tomorrow night.

**Comment by acdlite** [comment]
No problem. Thanks.

**Pull request merged**
