### PR TITLE
Ability to use inheritance with actions

### PR DESCRIPTION
**Pull request by netgusto**
Detection on method names in Actions._getActionMethodNames() is now able to inspect the class hierarchy to grab actions inherited from a potential base class.

### CODE REVIEW

**Comment by gurdasnijor** [comment]
I'm not convinced that inheritance for action classes would be something Flummox should support or encourage.

**Comment by acdlite** [comment]
Yes in fact the Action class will more than likely be removed in the next version in favor of plain objects (which are already supported). Let me know what problem you're trying to solve and I will suggest an alternative.

**Comment by gurdasnijor** [comment]
(Re-adding my accidentally deleted comment that @acdlite responded to for context)

"I'm not convinced that flummox actions should support inheritance; there isn't a meaningful hierarchical relationship between action classes"

**Comment by netgusto** [comment]
@acdlite "Let me know what problem you're trying to solve and I will suggest an alternative."

I'm trying to improve code re-use between my actions, as some of them share methods.

This is an idiomatic way to use ES6 classes, and though I understand why you wish to keep actions as 
flat and lean as possible, I believe that there's the need for inheritance in actions to improve code reuse, because mixins are on their way out, and actions can become pretty thick if you consider them not just as messengers, but as processors.

flummox should at least throw an explicit error when detecting that the action class does not implement directly the Actions base class, that might spare a lot of trouble to developers.

**Comment by acdlite** [comment]
> This is an idiomatic way to use ES6 classes

True. However, I've come to believe that classes were the wrong construct to use for Actions in the first place. They're really just groups of functions that have side effects. If you want to re-use actions, there are several other patterns you can use, including a function that returns a group of functions:

```js
function createCRUDActions(path) {
  return {
    async get(id) {
      const res = await fetch(`${path}/${id}`);
      return await res.json();
    }
    //...
  }
}
```

> because mixins are on their way out

Mixins are a form of inheritance, and they're "on their way out" in favor of composition, which `extends` definitely isn't.

**Pull request closed without merging**
